-- Run this once in the CurrentGradJobs Supabase SQL Editor.
create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  platform text not null unique check (platform in ('whatsapp', 'facebook', 'tiktok')),
  url text not null check (url ~* '^https://'),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.social_links enable row level security;

drop policy if exists "Public can view enabled social links" on public.social_links;
create policy "Public can view enabled social links" on public.social_links for select to anon, authenticated using (enabled = true);

drop policy if exists "Admins can manage social links" on public.social_links;
create policy "Admins can manage social links" on public.social_links for all to authenticated using (exists (select 1 from public.admin_users where admin_users.user_id = (select auth.uid()))) with check (exists (select 1 from public.admin_users where admin_users.user_id = (select auth.uid())));

-- Add your links after the table exists, or add them in the admin dashboard.
-- insert into public.social_links (platform, url) values
-- ('whatsapp', 'https://whatsapp.com/channel/your-channel'),
-- ('facebook', 'https://facebook.com/your-page'),
-- ('tiktok', 'https://tiktok.com/@your-account');
