import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient, getAdminUser } from '@/lib/supabase/server'
import SocialLinksForm from './SocialLinksForm'

export const dynamic = 'force-dynamic'
export default async function AdminPage() {
  const admin = await getAdminUser(); if (!admin) redirect('/admin/login')
  const supabase = await createClient(); const { data: jobs, error } = await supabase.from('jobs').select('id,title,company,location,job_type,closing_date,is_new').order('created_at', { ascending: false }); const { data: socialLinks } = await supabase.from('social_links').select('id,platform,url,enabled').order('platform')
  return <main className="min-h-screen bg-muted/30 px-6 py-10"><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><Link href="/" className="font-serif text-2xl font-black tracking-[-0.08em]">CurrentGradJobs</Link><h1 className="mt-8 text-4xl font-bold tracking-tight">Job dashboard</h1><p className="mt-2 text-muted-foreground">{jobs?.length ?? 0} live opportunities</p></div><div className="flex gap-3"><Link href="/admin/jobs/new" className="rounded-lg bg-primary px-4 py-3 font-semibold text-primary-foreground">Add job</Link><form action={async () => { 'use server'; const client = await createClient(); await client.auth.signOut(); redirect('/admin/login') }}><button className="rounded-lg border border-border bg-background px-4 py-3 font-semibold">Sign out</button></form></div></div>{error ? <p className="mt-8 rounded-lg border border-destructive/30 bg-destructive/10 p-4 text-destructive">Could not load jobs. Check your table policies.</p> : <div className="mt-8 overflow-hidden rounded-2xl border border-border bg-card"><div className="divide-y divide-border">{(jobs ?? []).map(job => <div key={job.id} className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div><h2 className="font-semibold">{job.title}</h2><p className="text-sm text-muted-foreground">{job.company} · {job.location} · {job.job_type}</p></div><div className="flex gap-2"><Link href={`/admin/jobs/${job.id}/edit`} className="rounded-lg border border-border px-3 py-2 text-sm font-medium">Edit</Link><form action={async () => { 'use server'; const client = await createClient(); await client.from('jobs').delete().eq('id', job.id); redirect('/admin') }}><button className="rounded-lg bg-destructive px-3 py-2 text-sm font-medium text-destructive-foreground">Delete</button></form></div></div>)}{jobs?.length === 0 && <p className="p-8 text-center text-muted-foreground">No jobs yet. Add your first opportunity.</p>}</div></div>}</div><SocialLinksForm links={socialLinks ?? []} /></main>
}
